title: Serkan Olgun
email: serkanolgun@gmail.com
# description: Personal Zone
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://serkanolgun.me" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: UA-171622371-1

# Social Profiles
github_username: skoofer
linkedin_username: serkan-olgun

# Build settings
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
